
data <- read.delim("/Users/Bova/Downloads/HBS_2021_RICOSTRUITICOICOP2018_IT/MICRODATI/HBS_Microdati_2021_RICOSTRUITICOICOP2018_DELIMITED.txt")
head(data)
str(data)
# rgn is the region of residence of the household, with 20 categories, let's see how many observations we have for each region
table(data$rgn)
# let's see the distribution of the variable "age" (age of the head of the household
summary(data$age)
# let's see the distribution of the variable "sex" (sex of the head of the household)
table(data$sex)
# let's see the distribution of the variable "educ" (education level of the head of the household)
table(data$educ)
# let's see the distribution of the variable "inc" (income of the household)
summary(data$inc)
# let's see the distribution of the variable "hhsize" (household size)
summary(data$hhsize)
# let's see the distribution of the variable "hhinc" (household income)
summary(data$hhinc)
# let's see the distribution of the variable "hhincpercap" (household income per capita)
summary(data$hhincpercap)
# let's see the distribution of the variable "hhincpercapdec" (household income per capita decile)
table(data$hhincpercapdec)  
